[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "cd server && npm run start"

[env]
NODE_ENV = "production"
VECTOR_DB = "lancedb"
LLM_PROVIDER = "openai"
EMBEDDING_ENGINE = "native"
TTS_PROVIDER = "native"
WHISPER_PROVIDER = "local"