[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "yarn render:build && cd server && yarn start"

[env]
NODE_ENV = "production"
VECTOR_DB = "lancedb"
LLM_PROVIDER = "openai"
EMBEDDING_ENGINE = "native"
TTS_PROVIDER = "native"
WHISPER_PROVIDER = "local"